name: Build and publish
on:
  push:
    tags:
      - "v*.*.*"  # Only trigger on tags like v1.2.3

jobs:
  build-and-release:
    name: Build EXE and Create Release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --icon=logo.ico --add-data "logo.ico;." --add-data "alarm.wav;." --add-data "ring.wav;." -n ConectorCordiax_debug conector_cordiax.py
          pyinstaller --onefile --windowed --icon=logo.ico --add-data "logo.ico;." --add-data "alarm.wav;." --add-data "ring.wav;." -n ConectorCordiax conector_cordiax.py


      - name: Create GitHub Release with EXE
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/ConectorCordiax.exe,dist/ConectorCordiax_debug.exe"
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }} - Conector Cordiax
          prerelease: false
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
